"""PDF assembly service. Converts report section content into a
print-optimized PDF using WeasyPrint.

Per CLAUDE.md: WeasyPrint with print-optimized CSS. Not Tailwind.
Per AGENTS.md: assemble_pdf() is called by assemble_and_deliver task.
"""

import html
import re
from datetime import date
from pathlib import Path

import weasyprint

CSS_PATH = Path(__file__).resolve().parent.parent / "templates" / "report.css"

# Section display names in master PDF order (CLAUDE.md product flow)
SECTION_ORDER = [
    ("offensive_sets", "Offensive Sets"),
    ("defensive_schemes", "Defensive Schemes"),
    ("pnr_coverage", "Pick and Roll Coverage"),
    ("player_pages", "Individual Player Pages"),
    ("game_plan", "Game Plan"),
    ("adjustments_practice", "In-Game Adjustments & Practice Plan"),
]


def assemble_pdf(
    sections: list[dict],
    team_name: str,
    report_date: date,
    is_partial: bool = False,
) -> bytes:
    """Build a PDF scouting report from section content.

    sections: list of dicts with keys section_type, status, content
    team_name: opponent team name for cover page
    report_date: report generation date
    is_partial: True if any sections errored

    Returns PDF bytes ready for R2 upload.
    """
    section_map = {s["section_type"]: s for s in sections}
    html_content = _build_html(section_map, team_name, report_date, is_partial)
    return weasyprint.HTML(string=html_content).write_pdf()


def _build_html(
    section_map: dict,
    team_name: str,
    report_date: date,
    is_partial: bool,
) -> str:
    """Build the complete HTML document for WeasyPrint rendering."""
    css = CSS_PATH.read_text() if CSS_PATH.exists() else ""

    cover = _build_cover_page(team_name, report_date)

    partial_banner = ""
    if is_partial:
        partial_banner = (
            '<div class="partial-banner">'
            "<p>PARTIAL REPORT — One or more sections could not be generated.</p>"
            "</div>"
        )

    sections_html = []
    for section_type, section_title in SECTION_ORDER:
        section = section_map.get(section_type, {})
        status = section.get("status", "error")
        content = section.get("content", "")

        if status == "complete" and content:
            body = _text_to_html(content)
            sections_html.append(
                f'<div class="section">'
                f"<h2>{html.escape(section_title)}</h2>"
                f"{body}"
                f"</div>"
            )
        else:
            sections_html.append(
                f'<div class="section section-error">'
                f"<h2>{html.escape(section_title)}</h2>"
                f'<p class="error-notice">'
                f"This section could not be generated. "
                f"Please contact support or regenerate the report."
                f"</p>"
                f"</div>"
            )

    return (
        "<!DOCTYPE html>\n"
        "<html>\n<head>\n"
        '<meta charset="utf-8">\n'
        f"<style>\n{css}\n</style>\n"
        "</head>\n<body>\n"
        f"{cover}\n"
        f"{partial_banner}\n"
        f"{''.join(sections_html)}\n"
        "</body>\n</html>"
    )


def _build_cover_page(team_name: str, report_date: date) -> str:
    date_str = report_date.strftime("%B %d, %Y")
    return (
        '<div class="cover-page">'
        '<div class="cover-content">'
        '<div class="cover-brand">TEX</div>'
        '<div class="cover-subtitle">Scouting Report</div>'
        '<div class="cover-divider"></div>'
        f'<div class="cover-team">{html.escape(team_name)}</div>'
        f'<div class="cover-date">{date_str}</div>'
        "</div>"
        '<div class="cover-footer">'
        "<p>Generated by TEX &mdash; AI-Powered Basketball Scouting</p>"
        "</div>"
        "</div>"
    )


def _text_to_html(text: str) -> str:
    """Convert AI-generated section text to HTML.

    Handles the output formats defined in PROMPTS.md: UPPERCASE headings,
    player profile blocks, bullet lists, trigger blocks, and paragraphs.
    """
    lines = text.split("\n")
    parts: list[str] = []
    in_list = False
    para_buf: list[str] = []

    def flush_para():
        nonlocal para_buf
        if para_buf:
            combined = " ".join(para_buf)
            parts.append(f"<p>{html.escape(combined)}</p>")
            para_buf = []

    def close_list():
        nonlocal in_list
        if in_list:
            parts.append("</ul>")
            in_list = False

    for line in lines:
        stripped = line.strip()

        # Blank line — flush accumulated paragraph text
        if not stripped:
            flush_para()
            close_list()
            continue

        # --- horizontal rule (player profile separator)
        if stripped == "---":
            flush_para()
            close_list()
            parts.append('<hr class="profile-break">')
            continue

        # Player header: #NUMBER NAME | POSITION
        if re.match(r"^#\d+\s", stripped):
            flush_para()
            close_list()
            parts.append(f'<h3 class="player-header">{html.escape(stripped)}</h3>')
            continue

        # TRIGGER N: header (section 6)
        if re.match(r"^TRIGGER\s+\d+", stripped):
            flush_para()
            close_list()
            parts.append(f'<h4 class="trigger-header">{html.escape(stripped)}</h4>')
            continue

        # Trigger detail lines: If: / Then: / Tell your team:
        trigger_match = re.match(r"^(If:|Then:|Tell your team:)\s*(.*)", stripped)
        if trigger_match:
            flush_para()
            label, rest = trigger_match.group(1), trigger_match.group(2)
            parts.append(
                f'<p class="trigger-detail">'
                f"<strong>{html.escape(label)}</strong> {html.escape(rest)}</p>"
            )
            continue

        # DAY N header (practice plan in section 6)
        if re.match(r"^DAY\s+\d+", stripped):
            flush_para()
            close_list()
            parts.append(f'<h4 class="day-header">{html.escape(stripped)}</h4>')
            continue

        # ALL CAPS line → section heading (5+ chars, all uppercase, has letters)
        if (
            len(stripped) > 4
            and stripped.upper() == stripped
            and re.search(r"[A-Z]", stripped)
            and not stripped.startswith("- ")
        ):
            flush_para()
            close_list()
            parts.append(f"<h3>{html.escape(stripped)}</h3>")
            continue

        # Bullet point
        if stripped.startswith("- ") or stripped.startswith("* "):
            flush_para()
            if not in_list:
                parts.append("<ul>")
                in_list = True
            parts.append(f"<li>{html.escape(stripped[2:])}</li>")
            continue

        # Regular text — accumulate for paragraph grouping
        if in_list:
            close_list()
        para_buf.append(stripped)

    flush_para()
    close_list()
    return "\n".join(parts)
